### ISSUE TITLE
"LexError" When running build.rs

### ISSUE THREAD

**Issue by syddf** [curldivergence/rusty-d3d12#1]
After installing LLVM, I tried to generate bindings by setting "Devel" feature
But I received this error log and I can't know what the real "lex error" is.

Trying to find d3d12.h at extern\D3D12AgilitySDK\include\d3d12.h
  thread 'main' panicked at C:\Users\yuanjinrui\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.60.1\src\codegen\mod.rs:4654:66:
  called `Result::unwrap()` on an `Err` value: LexError { span: Span }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\panicking.rs:645
     1: core::panicking::panic_fmt
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\core\src\result.rs:1653
     3: core::result::Result<T,E>::unwrap
     4: bindgen::codegen::utils::build_path
     5: <bindgen::ir::ty::Type as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     6: <bindgen::ir::item::Item as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     7: <T as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     8: <bindgen::ir::ty::Type as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     9: <bindgen::ir::item::Item as bindgen::codegen::TryToRustTy>::try_to_rust_ty
    10: <T as bindgen::codegen::TryToRustTy>::try_to_rust_ty
    11: <T as bindgen::codegen::ToRustTyOrOpaque>::to_rust_ty_or_opaque
    12: <bindgen::ir::comp::FieldData as bindgen::codegen::FieldCodegen>::codegen
    13: <bindgen::ir::comp::Field as bindgen::codegen::FieldCodegen>::codegen
    14: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    16: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    17: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    18: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    19: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    20: bindgen::codegen::codegen::{{closure}}
    21: bindgen::ir::context::BindgenContext::gen
    22: bindgen::codegen::codegen
    23: <bindgen::BindgenOptions as core::default::Default>::default
    24: bindgen::Builder::generate
    25: alloc::raw_vec::handle_reserve
    26: alloc::raw_vec::handle_reserve
    27: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by curldivergence** [comment]
Hi, thanks a lot for reporting this! Unfortunately I don’t have an access to a Windows machine right now, but I’ll try to find one in the next few days and look into this problem.

**Comment by syddf** [comment]
I added "devel" to "features" in "package.metadata.docs.rs" and updated the bindgen to the latest version.
These can solve the problem.
Thanks for you response, I will continue to learn this repo.

**Comment by curldivergence** [comment]
I'm glad it worked out for you! Please don't hesitate to ask if you have any questions :)
